apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: atlantis
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 4141
      protocol: TCP
  selector:
    app: atlantis
